import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync } from 'node:fs';
import mysql from 'mysql2/promise';
import { startTestDb, resetTestDb, testDbConfig } from '../support/testDb.js';

const REFERENCE_DB = 'via_reference';

/**
 * The baseline migration was generated by introspection and then edited by
 * hand, so this proves that running the migrations produces the same schema
 * that the frozen reference schema produces. That reference was verified against a
 * production dump on 2026-08-29, so matching it is matching production.
 */
async function describeSchema(conn, schema) {
  const [columns] = await conn.query(
    `SELECT table_name AS t, column_name AS c, column_type AS ty, is_nullable AS n,
            column_default AS d, extra AS e
       FROM information_schema.columns
      WHERE table_schema = ? AND table_name <> '__drizzle_migrations'
      ORDER BY table_name, column_name`, [schema]);
  const [indexes] = await conn.query(
    `SELECT table_name AS t, index_name AS i, seq_in_index AS s, column_name AS c,
            non_unique AS u
       FROM information_schema.statistics
      WHERE table_schema = ? AND table_name <> '__drizzle_migrations'
      ORDER BY table_name, index_name, seq_in_index`, [schema]);
  const [constraints] = await conn.query(
    `SELECT table_name AS t, constraint_name AS n, constraint_type AS ty
       FROM information_schema.table_constraints
      WHERE table_schema = ? AND table_name <> '__drizzle_migrations'
      ORDER BY table_name, constraint_name, constraint_type`, [schema]);
  const [checks] = await conn.query(
    `SELECT cc.constraint_name AS n, cc.check_clause AS clause
       FROM information_schema.check_constraints cc
      WHERE cc.constraint_schema = ? ORDER BY cc.constraint_name`, [schema]);
  return { columns, indexes, constraints, checks };
}

describe('baseline migration fidelity', () => {
  let migrated;
  let reference;

  beforeAll(async () => {
    await startTestDb();
    await resetTestDb();

    process.env.DB_HOST = testDbConfig.host;
    process.env.DB_PORT = String(testDbConfig.port);
    process.env.DB_USER = testDbConfig.user;
    process.env.DB_PASSWORD = testDbConfig.password;
    process.env.DB_NAME = testDbConfig.database;
    const { applyMigrations } = await import('../../db/migrate.ts');
    await applyMigrations();

    const conn = await mysql.createConnection({ ...testDbConfig, database: undefined });
    await conn.query(`DROP DATABASE IF EXISTS ${REFERENCE_DB}`);
    await conn.query(`CREATE DATABASE ${REFERENCE_DB}`);
    await conn.query(`USE ${REFERENCE_DB}`);
    await conn.query(
      readFileSync(new URL('../fixtures/verified-production-schema.sql', import.meta.url), 'utf8')
        .replace(/^CREATE DATABASE[^;]*;/m, '')
        .replace(/^USE [^;]*;/m, '')
    );

    migrated = await describeSchema(conn, testDbConfig.database);
    reference = await describeSchema(conn, REFERENCE_DB);
    await conn.query(`DROP DATABASE ${REFERENCE_DB}`);
    await conn.end();
  }, 180_000);

  it('creates the same columns as the schema of record', () => {
    expect(migrated.columns).toEqual(reference.columns);
  });

  it('creates the same indexes as the schema of record', () => {
    expect(migrated.indexes).toEqual(reference.indexes);
  });

  it('creates the same check clauses as the schema of record', () => {
    const clauses = c => c.checks.map(r => r.clause).sort();
    expect(clauses(migrated)).toEqual(clauses(reference));
  });

  it('creates the same table constraints as the schema of record', () => {
    expect(migrated.constraints).toEqual(reference.constraints);
  });

  it('records the migration in drizzle bookkeeping', async () => {
    const conn = await mysql.createConnection(testDbConfig);
    const [rows] = await conn.query(
      `SELECT COUNT(*) AS n FROM information_schema.tables
        WHERE table_schema = ? AND table_name = '__drizzle_migrations'`,
      [testDbConfig.database]
    );
    await conn.end();
    expect(Number(rows[0].n)).toBe(1);
  });
});
